version : '2'

services:
  reception:
    image: daniellavoie/sopra-reception:staging
    environment:
      - SPRING_PROFILES_ACTIVE=staging
      - MANAGEMENT_SECURITY_ENABLED=false
      
  shipping:
    image: daniellavoie/sopra-shipping:staging
    environment:
      - SPRING_PROFILES_ACTIVE=staging
      - MANAGEMENT_SECURITY_ENABLED=false

  purchase-order:
    image: daniellavoie/sopra-purchase-order:staging
    environment:
      - SPRING_PROFILES_ACTIVE=staging
      - MANAGEMENT_SECURITY_ENABLED=false

  sale:
    image: daniellavoie/sopra-sale:staging
    environment:
      - SPRING_PROFILES_ACTIVE=staging
      - MANAGEMENT_SECURITY_ENABLED=false

networks:
  traefik:
    external:
      name: traefik_default