version : '2'

services:
  reception:
    image: daniellavoie/sopra-reception:staging
    environment:
      - SPRING_PROFILES_ACTIVE=staging
      - MANAGEMENT_SECURITY_ENABLED=false

networks:
  traefik:
    external:
      name: traefik_default