version : '2'

services:
  eureka:
    image: daniellavoie/sopra-eureka:staging
    environment:
      - SPRING_PROFILES_ACTIVE=staging
      - MANAGEMENT_SECURITY_ENABLED=false
    ports:
      - "8761"
    labels:
      - "traefik.backend=staging-sopra-eureka"
      - "traefik.frontend.rule=Host:staging.sopra.eureka.cspinformatique.com"
      - "traefik.port=8761"
      - "traefik.docker.network=traefik_default"
    networks:
      - traefik
      - default

  config-server:
    image: daniellavoie/sopra-config-server:staging
    environment:
      - SPRING_PROFILES_ACTIVE=staging
      - MANAGEMENT_SECURITY_ENABLED=false

networks:
  traefik:
    external:
      name: traefik_default